# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B1yjfaQA6ESlDye1LzraOkDNbtk_KR_s
"""

year = int(input("Введите год: "))

if year % 400 == 0:
    print("да")
elif year % 100 == 0:
    print("нет")
elif year % 4 == 0:
    print("да")
else:
    print("нет")

