# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S5EoMTZ1_7g_ZvlvbVys_1vGvfy9OeM0
"""

y = int(input("Год: "))

if y % 400 == 0:
    print("да")
elif y % 100 == 0:
    print("нет")
elif y % 4 == 0:
    print("да")
else:
    print("нет")

y = int(input("Год: "))
is_leap = (y % 400 == 0) or (y % 4 == 0 and y % 100 != 0)

if is_leap:
    print("да")
else:
    print("нет")

y = int(input("Год: "))

answer = "нет"
if (y % 400 == 0) or (y % 4 == 0 and y % 100 != 0):
    answer = "да"

print(answer)